export const buildings = [
  {
    id: 0,
    name: "ASIC Miner",
    emoji: "⛏",
    desc: "Cheap ASIC Mining computer to mine on the Handshake Blockchain.",
    basePrice: 75,
    rate: 0.5,
  },
  {
    id: 1,
    name: "TLD Staking",
    emoji: "🏷",
    desc: "You stake one of your TLDs to allow SLD registrations. Nice!",
    basePrice: 500,
    rate: 5,
  },
  {
    id: 2,
    name: "Sniping Bot",
    emoji: "🤖",
    desc: "An bot programmed to automatically mint rare or expiring Handshake names.",
    basePrice: 5500,
    rate: 40,
  },
  {
    id: 3,
    name: "ICANN Proxy",
    emoji: "✈️",
    desc: "A proxy website to access Handshake sites through an ICANN domain.",
    basePrice: 60000,
    rate: 235,
  },
  {
    id: 4,
    name: "Nameserver",
    emoji: "🔌",
    desc: "An authoritative, public nameserver for setting DNS records for Handshake names.",
    basePrice: 650000,
    rate: 1300,
  },
  {
    id: 5,
    name: "Name Marketplace",
    emoji: "🛍",
    desc: "Online service for users to sell and purchase Handshake names.",
    basePrice: 7000000,
    rate: 7000,
  },
  {
    id: 6,
    name: "Registar",
    emoji: "📒",
    desc: "Your own Handshake name registrar to lease SLDs to users.",
    basePrice: 100000000,
    rate: 39000,
  },
  {
    id: 7,
    name: "HNS Exchange",
    emoji: "🏦",
    desc: "Online platform for exchanging HNS and other currencies.",
    basePrice: 1650000000,
    rate: 220000,
  },
];
